# Generated by Django 4.2.3 on 2023-08-06 05:13

import arrot.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GolsaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(choices=[('کاشت مژه', 'کاشت مژه'), ('کاشت ناخن', 'کاشت ناخن'), ('هایلایت ابرو', 'هایلایت ابرو')], verbose_name='نام خدمات')),
                ('hour', models.CharField(choices=[('08-10', '08-10'), ('10-12', '10-12'), ('12-14', '12-14'), ('14-16', '14-16'), ('16-18', '16-18')], max_length=5, verbose_name='زمان انتخابی')),
                ('date', django_jalali.db.models.jDateField(validators=[arrot.utils.passedDays, arrot.utils.noFriday], verbose_name='روز انتخابی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیح کوتاه')),
                ('admin_approval', models.BooleanField(default=False, verbose_name='تایید مدیر')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='به روز شده در')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('title', 'hour', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ArrotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(choices=[('هایفو تراپی', 'هایفو تراپی'), ('فشیال پاکسازی پوست', 'فشیال پاکسازی پوست'), ('تزریق بوتاکس', 'تزریق بوتاکس'), ('تزریق فیلر', 'تزریق فیلر'), ('تزریق ژل', 'تزریق ژل'), ('لیزر مو های زائد', 'لیزر مو های زائد'), ('مزو تراپی', 'مزو تراپی'), ('لاغری با دستگاه', 'لاغری با دستگاه'), ('مشاوره تغذیه', 'مشاوره تغذیه'), ('میکرونیدلینگ', 'میکرونیدلینگ')], verbose_name='نام خدمات')),
                ('hour', models.CharField(choices=[('08-10', '08-10'), ('10-12', '10-12'), ('12-14', '12-14'), ('14-16', '14-16'), ('16-18', '16-18')], max_length=5, verbose_name='زمان انتخابی')),
                ('date', django_jalali.db.models.jDateField(validators=[arrot.utils.passedDays, arrot.utils.noFriday], verbose_name='روز انتخابی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه')),
                ('admin_approval', models.BooleanField(default=False, verbose_name='تایید مدیر')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='به روز شده در')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('title', 'hour', 'date')},
            },
        ),
    ]
